[package]
name = "reticulum-migrations"
version.workspace = true
edition.workspace = true

[dependencies]
# Workspace dependencies
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls"] }
sea-orm-migration = "0.12"
async-std = { version = "1.12", features = ["attributes", "tokio1"] }
