[package]
name = "reticulum-migrations"
version.workspace = true
edition.workspace = true

[dependencies]
# Workspace dependencies
sea-orm-migration = { version = "0.12", default-features = false, features = [] }
sea-query = "0.30"
async-std = { version = "1.12", features = ["attributes", "tokio1"] }
